# Generated by Django 3.0.6 on 2021-01-15 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_orders_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='item_jason',
            new_name='item_json',
        ),
    ]
